services:
  app:
    image: echoai-app:latest
    container_name: echoai-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/echoaidb
      SPRING_DATASOURCE_USERNAME: echoai_user
      SPRING_DATASOURCE_PASSWORD: echoai_password

volumes:
  postgres_data: