services:
  db:
    image: echoai-db:latest
    environment:
      POSTGRES_DB: echoaidb
      POSTGRES_USER: echoai_user
      POSTGRES_PASSWORD: echoai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: