apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoai-app-deployment
  labels:
    app: echoai-app  
  annotations:
    redeploy: "true"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoai-app  
      role: app
  template:
    metadata:
      labels:
        app: echoai-app 
        role: app
    spec:
      containers:
        - name: spring-boot-container
          image: grexrr/echoai-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080  # 应用暴露的端口
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/echoaidb
            - name: SPRING_DATASOURCE_USERNAME
              value: "echoai_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "echoai_password"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"

---

apiVersion: v1
kind: Service
metadata:
  name: echoai-app-service
spec:
  selector:
    app: echoai-app
    role: app
  ports:
    - protocol: TCP
      port: 8080   # the exposed port
      targetPort: 8080  # the port the pods will listen on internally
  # for the bright future
  type: ClusterIP
